pointcloud_to_laserscan:
  pointcloud_to_laserscan:
    ros__parameters:
      range_min: 0.0
      # min_height: 2.2e-308

async_slam_toolbox:
  ros__parameters:
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping #localization

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 4.0
      publish_frequency: 4.0
      global_frame: map
      robot_base_frame: base_link
      # use_sim_time: true
      rolling_window: true
      footprint: "[ [0.4725,-0.365], [0.4725,0.365], [-0.4725,0.365], [-0.4725,-0.365] ]"
      width: 3.0
      height: 3.0
      resolution: 0.1

      plugins: ["voxel_layer", "inflation_layer"]
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: true
        publish_voxel_map: true
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        unknown_threshold: 15
        observation_sources: velodyne depth_camera
        combination_method: 1
        velodyne:
          topic: /choo_2/velodyne_points
          data_type: "PointCloud2"
          marking: true
          clearing: true
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
        depth_camera:
          topic: /choo_2/depth_cam/points
          data_type: "PointCloud2"
          marking: true
          clearing: true
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.25
        cost_scaling_factor: 1.0
        inflate_unknown: false
        inflate_around_unknown: true

      always_send_full_costmap: true

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05